import { Router } from 'express';
import { movieController } from '../controllers/movie.controller.js';

const movieRoutes = Router();

/**
 * @openapi
 * components:
 *  schemas:
 *      movie:
 *          type: object
 *          properties:
 *              id:
 *                  type: string
 *                  description: the autogenerated id of the movie
 *              title:
 *                  type: string
 *                  description: title of the movie
 *              year:
 *                  type: integer
 *                  description: year of the movie
 *              available:
 *                  type: boolean
 *                  description: if movie is available for rent
 *              cast:
 *                  type: object
 *                  description: main cast
 *              genre:
 *                  type: object
 *                  description: genres of the movie
 *          example:
 *              id: 605b6485f0f9462918e51952
 *              title: Interstellar
 *              year: 2013
 *              cast: [actor1, actor2]
 *              genre: [genre1, genre2]
 */

movieRoutes.get("/", movieController.listMovies);
movieRoutes.get("/id/:id", movieController.findMovieById);
movieRoutes.get("/title/:title", movieController.findMovieByTitle);
movieRoutes.get("/cast/:cast", movieController.findByCast);
movieRoutes.get("/genre/:genre", movieController.findByGenre);

export default movieRoutes;